// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDeliveryInfo = "delivery_info"

// DeliveryInfo mapped from table <delivery_info>
type DeliveryInfo struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;comment:发货信息id" json:"id"`                           // 发货信息id
	AccountID       int64     `gorm:"column:account_id;type:bigint;not null;comment:所属账户id" json:"account_id"`             // 所属账户id
	ReceiverName    string    `gorm:"column:receiver_name;type:varchar(64);not null;comment:收货人姓名" json:"receiver_name"`   // 收货人姓名
	ReceiverPhone   string    `gorm:"column:receiver_phone;type:varchar(64);not null;comment:收货人电话" json:"receiver_phone"` // 收货人电话
	ReceiverAddress string    `gorm:"column:receiver_address;type:text;not null;comment:收货地址" json:"receiver_address"`     // 收货地址
	Extra           string    `gorm:"column:extra;type:json;not null;comment:额外信息" json:"extra"`                           // 额外信息
	IsDeleted       bool      `gorm:"column:is_deleted;type:tinyint(1);not null" json:"is_deleted"`
	CreateTime      time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime      time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName DeliveryInfo's table name
func (*DeliveryInfo) TableName() string {
	return TableNameDeliveryInfo
}
