// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePaymentInfo = "payment_info"

// PaymentInfo mapped from table <payment_info>
type PaymentInfo struct {
	ID           int64      `gorm:"column:id;type:bigint;primaryKey;comment:支付信息id" json:"id"`                              // 支付信息id
	TradeOrderID int64      `gorm:"column:trade_order_id;type:bigint;not null;comment:交易单id" json:"trade_order_id"`         // 交易单id
	PaymentNo    string     `gorm:"column:payment_no;type:varchar(64);not null;comment:支付单号" json:"payment_no"`             // 支付单号
	PayScene     int32      `gorm:"column:pay_scene;type:int;not null;comment:支付场景，如下单支付、退款支付等" json:"pay_scene"`           // 支付场景，如下单支付、退款支付等
	PaidAmount   int64      `gorm:"column:paid_amount;type:bigint;not null;comment:支付金额，单位：厘" json:"paid_amount"`           // 支付金额，单位：厘
	PayChannel   int32      `gorm:"column:pay_channel;type:int;not null;comment:支付渠道，如余额支付、微信支付、支付宝支付等" json:"pay_channel"` // 支付渠道，如余额支付、微信支付、支付宝支付等
	PayStatus    int32      `gorm:"column:pay_status;type:int;not null;comment:支付状态，如未支付、已支付、支付失败等" json:"pay_status"`      // 支付状态，如未支付、已支付、支付失败等
	PayTime      *time.Time `gorm:"column:pay_time;type:timestamp;comment:支付时间" json:"pay_time"`                            // 支付时间
	CloseTime    *time.Time `gorm:"column:close_time;type:timestamp;comment:关单时间" json:"close_time"`                        // 关单时间
	SuccessTime  *time.Time `gorm:"column:success_time;type:timestamp;comment:支付成功时间" json:"success_time"`                  // 支付成功时间
	IsDeleted    bool       `gorm:"column:is_deleted;type:tinyint(1);not null" json:"is_deleted"`
	CreateTime   time.Time  `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime   time.Time  `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName PaymentInfo's table name
func (*PaymentInfo) TableName() string {
	return TableNamePaymentInfo
}
