// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePromotion = "promotion"

// Promotion mapped from table <promotion>
type Promotion struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;comment:优惠id" json:"id"`                                      // 优惠id
	Name            string     `gorm:"column:name;type:varchar(64);not null;comment:优惠名称" json:"name"`                               // 优惠名称
	Description     string     `gorm:"column:description;type:text;not null;comment:优惠描述" json:"description"`                        // 优惠描述
	PromotionType   int32      `gorm:"column:promotion_type;type:int;not null;comment:优惠类型，如满减、折扣等" json:"promotion_type"`           // 优惠类型，如满减、折扣等
	PromotionRule   string     `gorm:"column:promotion_rule;type:json;not null;comment:优惠规则" json:"promotion_rule"`                  // 优惠规则
	PromotionStatus int32      `gorm:"column:promotion_status;type:int;not null;comment:优惠状态，如未开始、进行中、已结束等" json:"promotion_status"` // 优惠状态，如未开始、进行中、已结束等
	StartTime       *time.Time `gorm:"column:start_time;type:timestamp;comment:优惠开始时间" json:"start_time"`                            // 优惠开始时间
	EndTime         *time.Time `gorm:"column:end_time;type:timestamp;comment:优惠结束时间" json:"end_time"`                                // 优惠结束时间
	IsDeleted       bool       `gorm:"column:is_deleted;type:tinyint(1);not null" json:"is_deleted"`
	CreateTime      time.Time  `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime      time.Time  `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Promotion's table name
func (*Promotion) TableName() string {
	return TableNamePromotion
}
