// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameRefundOrder = "refund_order"

// RefundOrder mapped from table <refund_order>
type RefundOrder struct {
	ID           int64      `gorm:"column:id;type:bigint;primaryKey;comment:退款单id" json:"id"`                                // 退款单id
	TradeOrderID int64      `gorm:"column:trade_order_id;type:bigint;not null;comment:交易单id" json:"trade_order_id"`          // 交易单id
	PaymentID    int64      `gorm:"column:payment_id;type:bigint;not null;comment:支付信息id" json:"payment_id"`                 // 支付信息id
	RefundNo     string     `gorm:"column:refund_no;type:varchar(64);not null;comment:退款单号" json:"refund_no"`                // 退款单号
	RefundAmount int64      `gorm:"column:refund_amount;type:bigint;not null;comment:退款金额，单位：厘" json:"refund_amount"`        // 退款金额，单位：厘
	RefundStatus int32      `gorm:"column:refund_status;type:int;not null;comment:退款状态，如未退款、已退款、退款失败等" json:"refund_status"` // 退款状态，如未退款、已退款、退款失败等
	RefundType   int32      `gorm:"column:refund_type;type:int;not null;comment:退款类型，如仅退款、退货退款等" json:"refund_type"`         // 退款类型，如仅退款、退货退款等
	RefundReason string     `gorm:"column:refund_reason;type:text;not null;comment:退款原因" json:"refund_reason"`               // 退款原因
	RefundTime   *time.Time `gorm:"column:refund_time;type:timestamp;comment:退款时间" json:"refund_time"`                       // 退款时间
	IsDeleted    bool       `gorm:"column:is_deleted;type:tinyint(1);not null" json:"is_deleted"`
	CreateTime   time.Time  `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	CloseTime    *time.Time `gorm:"column:close_time;type:timestamp;comment:关单时间" json:"close_time"` // 关单时间
	UpdateTime   time.Time  `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName RefundOrder's table name
func (*RefundOrder) TableName() string {
	return TableNameRefundOrder
}
