// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTradePromotion = "trade_promotion"

// TradePromotion mapped from table <trade_promotion>
type TradePromotion struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;comment:具体优惠id" json:"id"`                          // 具体优惠id
	PromotionID   int64     `gorm:"column:promotion_id;type:bigint;not null;comment:优惠id" json:"promotion_id"`          // 优惠id
	Amount        int64     `gorm:"column:amount;type:bigint;not null;comment:优惠金额，单位：厘" json:"amount"`                 // 优惠金额，单位：厘
	PromotionType int32     `gorm:"column:promotion_type;type:int;not null;comment:优惠类型，如满减、折扣等" json:"promotion_type"` // 优惠类型，如满减、折扣等
	AccountID     int64     `gorm:"column:account_id;type:bigint;not null;comment:账户id" json:"account_id"`              // 账户id
	IsDeleted     bool      `gorm:"column:is_deleted;type:tinyint(1);not null" json:"is_deleted"`
	CreateTime    time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime    time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName TradePromotion's table name
func (*TradePromotion) TableName() string {
	return TableNameTradePromotion
}
