// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTradeOrder = "trade_order"

// TradeOrder mapped from table <trade_order>
type TradeOrder struct {
	ID                     int64      `gorm:"column:id;type:bigint;primaryKey;comment:交易单id" json:"id"`                                                       // 交易单id
	BizType                int32      `gorm:"column:biz_type;type:int;not null;comment:业务类型，如DouTok充值、商城订单等" json:"biz_type"`                                 // 业务类型，如DouTok充值、商城订单等
	SaleWay                int32      `gorm:"column:sale_way;type:int;not null;comment:销售方式，如直接销售、代理销售等" json:"sale_way"`                                     // 销售方式，如直接销售、代理销售等
	PaySequence            int32      `gorm:"column:pay_sequence;type:int;not null;comment:支付顺序, 如先支付、后支付" json:"pay_sequence"`                               // 支付顺序, 如先支付、后支付
	GoodsType              int32      `gorm:"column:goods_type;type:int;not null;comment:商品类型，如普通商品、虚拟商品、优惠券等" json:"goods_type"`                             // 商品类型，如普通商品、虚拟商品、优惠券等
	Status                 int32      `gorm:"column:status;type:int;not null;comment:交易单状态，如已创建、已支付、开始交付、交付完成等" json:"status"`                                // 交易单状态，如已创建、已支付、开始交付、交付完成等
	BizStatus              int64      `gorm:"column:biz_status;type:bigint;not null;comment:业务状态" json:"biz_status"`                                          // 业务状态
	BizOrderNo             string     `gorm:"column:biz_order_no;type:varchar(64);not null;comment:业务订单号" json:"biz_order_no"`                                // 业务订单号
	BizID                  int64      `gorm:"column:biz_id;type:bigint;not null;comment:业务id" json:"biz_id"`                                                  // 业务id
	BuyerID                int64      `gorm:"column:buyer_id;type:bigint;not null;comment:买家id" json:"buyer_id"`                                              // 买家id
	SellerID               int64      `gorm:"column:seller_id;type:bigint;not null;comment:卖家id" json:"seller_id"`                                            // 卖家id
	PayType                int32      `gorm:"column:pay_type;type:int;not null;comment:支付类型，如余额支付、微信支付、支付宝支付等" json:"pay_type"`                               // 支付类型，如余额支付、微信支付、支付宝支付等
	PayableAmount          int64      `gorm:"column:payable_amount;type:bigint;not null;comment:应付金额，单位：厘" json:"payable_amount"`                             // 应付金额，单位：厘
	PaidAmount             int64      `gorm:"column:paid_amount;type:bigint;not null;comment:已支付金额，单位：厘" json:"paid_amount"`                                  // 已支付金额，单位：厘
	PromotionAmount        int64      `gorm:"column:promotion_amount;type:bigint;not null;comment:优惠金额，单位：厘" json:"promotion_amount"`                         // 优惠金额，单位：厘
	DeliveryInfoID         int64      `gorm:"column:delivery_info_id;type:bigint;not null;comment:发货信息id" json:"delivery_info_id"`                            // 发货信息id
	DeliveryTime           *time.Time `gorm:"column:delivery_time;type:timestamp;comment:发货时间" json:"delivery_time"`                                          // 发货时间
	PaymentInfoID          int64      `gorm:"column:payment_info_id;type:bigint;not null;comment:支付信息id" json:"payment_info_id"`                              // 支付信息id
	PayTime                *time.Time `gorm:"column:pay_time;type:timestamp;comment:支付时间" json:"pay_time"`                                                    // 支付时间
	CloseTime              *time.Time `gorm:"column:close_time;type:timestamp;comment:关单时间" json:"close_time"`                                                // 关单时间
	CloseType              int32      `gorm:"column:close_type;type:int;not null;comment:关单类型" json:"close_type"`                                             // 关单类型
	CloseReason            string     `gorm:"column:close_reason;type:text;not null;comment:关单原因" json:"close_reason"`                                        // 关单原因
	Extra                  string     `gorm:"column:extra;type:json;not null;comment:额外信息" json:"extra"`                                                      // 额外信息
	TradeOrderRelation     int32      `gorm:"column:trade_order_relation;type:int;not null;comment:交易单类型" json:"trade_order_relation"`                        // 交易单类型
	OriginOrderID          int64      `gorm:"column:origin_order_id;type:bigint;not null;comment:原始订单id" json:"origin_order_id"`                              // 原始订单id
	ExpectPayTimeOut       *time.Time `gorm:"column:expect_pay_time_out;type:timestamp;comment:预期支付超时时间" json:"expect_pay_time_out"`                          // 预期支付超时时间
	ActualPayTimeOut       *time.Time `gorm:"column:actual_pay_time_out;type:timestamp;comment:实际支付超时时间" json:"actual_pay_time_out"`                          // 实际支付超时时间
	ExecuteAfterPayTimeOut bool       `gorm:"column:execute_after_pay_time_out;type:tinyint(1);not null;comment:支付超时后是否执行" json:"execute_after_pay_time_out"` // 支付超时后是否执行
	IsDeleted              bool       `gorm:"column:is_deleted;type:tinyint(1);not null" json:"is_deleted"`
	CreateTime             time.Time  `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime             time.Time  `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName TradeOrder's table name
func (*TradeOrder) TableName() string {
	return TableNameTradeOrder
}
