app:
  name: launcher-example
  version: 0.0.1-test

components:
  redis:
    default:
      dsn: localhost:6379
      password: root
  mysql:
    default:
      host: localhost
      port: 3306
      db_name: doutok
      user: root
      password: root
  etcd:
    default:
      host: localhost
      port: 2379
  minio:
    default:
      host: localhost
      port: 9000
      console_port: 9001
      access_key: root
      secret_key: rootroot
