// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cloudzenith/DouTok/backend/baseService/internal/infrastructure/dal/models"
)

func newDeliveryInfo(db *gorm.DB, opts ...gen.DOOption) deliveryInfo {
	_deliveryInfo := deliveryInfo{}

	_deliveryInfo.deliveryInfoDo.UseDB(db, opts...)
	_deliveryInfo.deliveryInfoDo.UseModel(&models.DeliveryInfo{})

	tableName := _deliveryInfo.deliveryInfoDo.TableName()
	_deliveryInfo.ALL = field.NewAsterisk(tableName)
	_deliveryInfo.ID = field.NewInt64(tableName, "id")
	_deliveryInfo.AccountID = field.NewInt64(tableName, "account_id")
	_deliveryInfo.ReceiverName = field.NewString(tableName, "receiver_name")
	_deliveryInfo.ReceiverPhone = field.NewString(tableName, "receiver_phone")
	_deliveryInfo.ReceiverAddress = field.NewString(tableName, "receiver_address")
	_deliveryInfo.Extra = field.NewString(tableName, "extra")
	_deliveryInfo.IsDeleted = field.NewBool(tableName, "is_deleted")
	_deliveryInfo.CreateTime = field.NewTime(tableName, "create_time")
	_deliveryInfo.UpdateTime = field.NewTime(tableName, "update_time")

	_deliveryInfo.fillFieldMap()

	return _deliveryInfo
}

type deliveryInfo struct {
	deliveryInfoDo

	ALL             field.Asterisk
	ID              field.Int64  // 发货信息id
	AccountID       field.Int64  // 所属账户id
	ReceiverName    field.String // 收货人姓名
	ReceiverPhone   field.String // 收货人电话
	ReceiverAddress field.String // 收货地址
	Extra           field.String // 额外信息
	IsDeleted       field.Bool
	CreateTime      field.Time
	UpdateTime      field.Time

	fieldMap map[string]field.Expr
}

func (d deliveryInfo) Table(newTableName string) *deliveryInfo {
	d.deliveryInfoDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deliveryInfo) As(alias string) *deliveryInfo {
	d.deliveryInfoDo.DO = *(d.deliveryInfoDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deliveryInfo) updateTableName(table string) *deliveryInfo {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.AccountID = field.NewInt64(table, "account_id")
	d.ReceiverName = field.NewString(table, "receiver_name")
	d.ReceiverPhone = field.NewString(table, "receiver_phone")
	d.ReceiverAddress = field.NewString(table, "receiver_address")
	d.Extra = field.NewString(table, "extra")
	d.IsDeleted = field.NewBool(table, "is_deleted")
	d.CreateTime = field.NewTime(table, "create_time")
	d.UpdateTime = field.NewTime(table, "update_time")

	d.fillFieldMap()

	return d
}

func (d *deliveryInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deliveryInfo) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 9)
	d.fieldMap["id"] = d.ID
	d.fieldMap["account_id"] = d.AccountID
	d.fieldMap["receiver_name"] = d.ReceiverName
	d.fieldMap["receiver_phone"] = d.ReceiverPhone
	d.fieldMap["receiver_address"] = d.ReceiverAddress
	d.fieldMap["extra"] = d.Extra
	d.fieldMap["is_deleted"] = d.IsDeleted
	d.fieldMap["create_time"] = d.CreateTime
	d.fieldMap["update_time"] = d.UpdateTime
}

func (d deliveryInfo) clone(db *gorm.DB) deliveryInfo {
	d.deliveryInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deliveryInfo) replaceDB(db *gorm.DB) deliveryInfo {
	d.deliveryInfoDo.ReplaceDB(db)
	return d
}

type deliveryInfoDo struct{ gen.DO }

type IDeliveryInfoDo interface {
	gen.SubQuery
	Debug() IDeliveryInfoDo
	WithContext(ctx context.Context) IDeliveryInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeliveryInfoDo
	WriteDB() IDeliveryInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeliveryInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeliveryInfoDo
	Not(conds ...gen.Condition) IDeliveryInfoDo
	Or(conds ...gen.Condition) IDeliveryInfoDo
	Select(conds ...field.Expr) IDeliveryInfoDo
	Where(conds ...gen.Condition) IDeliveryInfoDo
	Order(conds ...field.Expr) IDeliveryInfoDo
	Distinct(cols ...field.Expr) IDeliveryInfoDo
	Omit(cols ...field.Expr) IDeliveryInfoDo
	Join(table schema.Tabler, on ...field.Expr) IDeliveryInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeliveryInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeliveryInfoDo
	Group(cols ...field.Expr) IDeliveryInfoDo
	Having(conds ...gen.Condition) IDeliveryInfoDo
	Limit(limit int) IDeliveryInfoDo
	Offset(offset int) IDeliveryInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeliveryInfoDo
	Unscoped() IDeliveryInfoDo
	Create(values ...*models.DeliveryInfo) error
	CreateInBatches(values []*models.DeliveryInfo, batchSize int) error
	Save(values ...*models.DeliveryInfo) error
	First() (*models.DeliveryInfo, error)
	Take() (*models.DeliveryInfo, error)
	Last() (*models.DeliveryInfo, error)
	Find() ([]*models.DeliveryInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.DeliveryInfo, err error)
	FindInBatches(result *[]*models.DeliveryInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.DeliveryInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeliveryInfoDo
	Assign(attrs ...field.AssignExpr) IDeliveryInfoDo
	Joins(fields ...field.RelationField) IDeliveryInfoDo
	Preload(fields ...field.RelationField) IDeliveryInfoDo
	FirstOrInit() (*models.DeliveryInfo, error)
	FirstOrCreate() (*models.DeliveryInfo, error)
	FindByPage(offset int, limit int) (result []*models.DeliveryInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeliveryInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deliveryInfoDo) Debug() IDeliveryInfoDo {
	return d.withDO(d.DO.Debug())
}

func (d deliveryInfoDo) WithContext(ctx context.Context) IDeliveryInfoDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deliveryInfoDo) ReadDB() IDeliveryInfoDo {
	return d.Clauses(dbresolver.Read)
}

func (d deliveryInfoDo) WriteDB() IDeliveryInfoDo {
	return d.Clauses(dbresolver.Write)
}

func (d deliveryInfoDo) Session(config *gorm.Session) IDeliveryInfoDo {
	return d.withDO(d.DO.Session(config))
}

func (d deliveryInfoDo) Clauses(conds ...clause.Expression) IDeliveryInfoDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deliveryInfoDo) Returning(value interface{}, columns ...string) IDeliveryInfoDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deliveryInfoDo) Not(conds ...gen.Condition) IDeliveryInfoDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deliveryInfoDo) Or(conds ...gen.Condition) IDeliveryInfoDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deliveryInfoDo) Select(conds ...field.Expr) IDeliveryInfoDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deliveryInfoDo) Where(conds ...gen.Condition) IDeliveryInfoDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deliveryInfoDo) Order(conds ...field.Expr) IDeliveryInfoDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deliveryInfoDo) Distinct(cols ...field.Expr) IDeliveryInfoDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deliveryInfoDo) Omit(cols ...field.Expr) IDeliveryInfoDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deliveryInfoDo) Join(table schema.Tabler, on ...field.Expr) IDeliveryInfoDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deliveryInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeliveryInfoDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deliveryInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeliveryInfoDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deliveryInfoDo) Group(cols ...field.Expr) IDeliveryInfoDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deliveryInfoDo) Having(conds ...gen.Condition) IDeliveryInfoDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deliveryInfoDo) Limit(limit int) IDeliveryInfoDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deliveryInfoDo) Offset(offset int) IDeliveryInfoDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deliveryInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeliveryInfoDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deliveryInfoDo) Unscoped() IDeliveryInfoDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deliveryInfoDo) Create(values ...*models.DeliveryInfo) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deliveryInfoDo) CreateInBatches(values []*models.DeliveryInfo, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deliveryInfoDo) Save(values ...*models.DeliveryInfo) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deliveryInfoDo) First() (*models.DeliveryInfo, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.DeliveryInfo), nil
	}
}

func (d deliveryInfoDo) Take() (*models.DeliveryInfo, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.DeliveryInfo), nil
	}
}

func (d deliveryInfoDo) Last() (*models.DeliveryInfo, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.DeliveryInfo), nil
	}
}

func (d deliveryInfoDo) Find() ([]*models.DeliveryInfo, error) {
	result, err := d.DO.Find()
	return result.([]*models.DeliveryInfo), err
}

func (d deliveryInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.DeliveryInfo, err error) {
	buf := make([]*models.DeliveryInfo, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deliveryInfoDo) FindInBatches(result *[]*models.DeliveryInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deliveryInfoDo) Attrs(attrs ...field.AssignExpr) IDeliveryInfoDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deliveryInfoDo) Assign(attrs ...field.AssignExpr) IDeliveryInfoDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deliveryInfoDo) Joins(fields ...field.RelationField) IDeliveryInfoDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deliveryInfoDo) Preload(fields ...field.RelationField) IDeliveryInfoDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deliveryInfoDo) FirstOrInit() (*models.DeliveryInfo, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.DeliveryInfo), nil
	}
}

func (d deliveryInfoDo) FirstOrCreate() (*models.DeliveryInfo, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.DeliveryInfo), nil
	}
}

func (d deliveryInfoDo) FindByPage(offset int, limit int) (result []*models.DeliveryInfo, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deliveryInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deliveryInfoDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deliveryInfoDo) Delete(models ...*models.DeliveryInfo) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deliveryInfoDo) withDO(do gen.Dao) *deliveryInfoDo {
	d.DO = *do.(*gen.DO)
	return d
}
