// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cloudzenith/DouTok/backend/baseService/internal/infrastructure/dal/models"
)

func newPaymentInfo(db *gorm.DB, opts ...gen.DOOption) paymentInfo {
	_paymentInfo := paymentInfo{}

	_paymentInfo.paymentInfoDo.UseDB(db, opts...)
	_paymentInfo.paymentInfoDo.UseModel(&models.PaymentInfo{})

	tableName := _paymentInfo.paymentInfoDo.TableName()
	_paymentInfo.ALL = field.NewAsterisk(tableName)
	_paymentInfo.ID = field.NewInt64(tableName, "id")
	_paymentInfo.TradeOrderID = field.NewInt64(tableName, "trade_order_id")
	_paymentInfo.PaymentNo = field.NewString(tableName, "payment_no")
	_paymentInfo.PayScene = field.NewInt32(tableName, "pay_scene")
	_paymentInfo.PaidAmount = field.NewInt64(tableName, "paid_amount")
	_paymentInfo.PayChannel = field.NewInt32(tableName, "pay_channel")
	_paymentInfo.PayStatus = field.NewInt32(tableName, "pay_status")
	_paymentInfo.PayTime = field.NewTime(tableName, "pay_time")
	_paymentInfo.CloseTime = field.NewTime(tableName, "close_time")
	_paymentInfo.SuccessTime = field.NewTime(tableName, "success_time")
	_paymentInfo.IsDeleted = field.NewBool(tableName, "is_deleted")
	_paymentInfo.CreateTime = field.NewTime(tableName, "create_time")
	_paymentInfo.UpdateTime = field.NewTime(tableName, "update_time")

	_paymentInfo.fillFieldMap()

	return _paymentInfo
}

type paymentInfo struct {
	paymentInfoDo

	ALL          field.Asterisk
	ID           field.Int64  // 支付信息id
	TradeOrderID field.Int64  // 交易单id
	PaymentNo    field.String // 支付单号
	PayScene     field.Int32  // 支付场景，如下单支付、退款支付等
	PaidAmount   field.Int64  // 支付金额，单位：厘
	PayChannel   field.Int32  // 支付渠道，如余额支付、微信支付、支付宝支付等
	PayStatus    field.Int32  // 支付状态，如未支付、已支付、支付失败等
	PayTime      field.Time   // 支付时间
	CloseTime    field.Time   // 关单时间
	SuccessTime  field.Time   // 支付成功时间
	IsDeleted    field.Bool
	CreateTime   field.Time
	UpdateTime   field.Time

	fieldMap map[string]field.Expr
}

func (p paymentInfo) Table(newTableName string) *paymentInfo {
	p.paymentInfoDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentInfo) As(alias string) *paymentInfo {
	p.paymentInfoDo.DO = *(p.paymentInfoDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentInfo) updateTableName(table string) *paymentInfo {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.TradeOrderID = field.NewInt64(table, "trade_order_id")
	p.PaymentNo = field.NewString(table, "payment_no")
	p.PayScene = field.NewInt32(table, "pay_scene")
	p.PaidAmount = field.NewInt64(table, "paid_amount")
	p.PayChannel = field.NewInt32(table, "pay_channel")
	p.PayStatus = field.NewInt32(table, "pay_status")
	p.PayTime = field.NewTime(table, "pay_time")
	p.CloseTime = field.NewTime(table, "close_time")
	p.SuccessTime = field.NewTime(table, "success_time")
	p.IsDeleted = field.NewBool(table, "is_deleted")
	p.CreateTime = field.NewTime(table, "create_time")
	p.UpdateTime = field.NewTime(table, "update_time")

	p.fillFieldMap()

	return p
}

func (p *paymentInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentInfo) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 13)
	p.fieldMap["id"] = p.ID
	p.fieldMap["trade_order_id"] = p.TradeOrderID
	p.fieldMap["payment_no"] = p.PaymentNo
	p.fieldMap["pay_scene"] = p.PayScene
	p.fieldMap["paid_amount"] = p.PaidAmount
	p.fieldMap["pay_channel"] = p.PayChannel
	p.fieldMap["pay_status"] = p.PayStatus
	p.fieldMap["pay_time"] = p.PayTime
	p.fieldMap["close_time"] = p.CloseTime
	p.fieldMap["success_time"] = p.SuccessTime
	p.fieldMap["is_deleted"] = p.IsDeleted
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["update_time"] = p.UpdateTime
}

func (p paymentInfo) clone(db *gorm.DB) paymentInfo {
	p.paymentInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentInfo) replaceDB(db *gorm.DB) paymentInfo {
	p.paymentInfoDo.ReplaceDB(db)
	return p
}

type paymentInfoDo struct{ gen.DO }

type IPaymentInfoDo interface {
	gen.SubQuery
	Debug() IPaymentInfoDo
	WithContext(ctx context.Context) IPaymentInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentInfoDo
	WriteDB() IPaymentInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentInfoDo
	Not(conds ...gen.Condition) IPaymentInfoDo
	Or(conds ...gen.Condition) IPaymentInfoDo
	Select(conds ...field.Expr) IPaymentInfoDo
	Where(conds ...gen.Condition) IPaymentInfoDo
	Order(conds ...field.Expr) IPaymentInfoDo
	Distinct(cols ...field.Expr) IPaymentInfoDo
	Omit(cols ...field.Expr) IPaymentInfoDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentInfoDo
	Group(cols ...field.Expr) IPaymentInfoDo
	Having(conds ...gen.Condition) IPaymentInfoDo
	Limit(limit int) IPaymentInfoDo
	Offset(offset int) IPaymentInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentInfoDo
	Unscoped() IPaymentInfoDo
	Create(values ...*models.PaymentInfo) error
	CreateInBatches(values []*models.PaymentInfo, batchSize int) error
	Save(values ...*models.PaymentInfo) error
	First() (*models.PaymentInfo, error)
	Take() (*models.PaymentInfo, error)
	Last() (*models.PaymentInfo, error)
	Find() ([]*models.PaymentInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.PaymentInfo, err error)
	FindInBatches(result *[]*models.PaymentInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.PaymentInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentInfoDo
	Assign(attrs ...field.AssignExpr) IPaymentInfoDo
	Joins(fields ...field.RelationField) IPaymentInfoDo
	Preload(fields ...field.RelationField) IPaymentInfoDo
	FirstOrInit() (*models.PaymentInfo, error)
	FirstOrCreate() (*models.PaymentInfo, error)
	FindByPage(offset int, limit int) (result []*models.PaymentInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentInfoDo) Debug() IPaymentInfoDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentInfoDo) WithContext(ctx context.Context) IPaymentInfoDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentInfoDo) ReadDB() IPaymentInfoDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentInfoDo) WriteDB() IPaymentInfoDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentInfoDo) Session(config *gorm.Session) IPaymentInfoDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentInfoDo) Clauses(conds ...clause.Expression) IPaymentInfoDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentInfoDo) Returning(value interface{}, columns ...string) IPaymentInfoDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentInfoDo) Not(conds ...gen.Condition) IPaymentInfoDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentInfoDo) Or(conds ...gen.Condition) IPaymentInfoDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentInfoDo) Select(conds ...field.Expr) IPaymentInfoDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentInfoDo) Where(conds ...gen.Condition) IPaymentInfoDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentInfoDo) Order(conds ...field.Expr) IPaymentInfoDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentInfoDo) Distinct(cols ...field.Expr) IPaymentInfoDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentInfoDo) Omit(cols ...field.Expr) IPaymentInfoDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentInfoDo) Join(table schema.Tabler, on ...field.Expr) IPaymentInfoDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentInfoDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentInfoDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentInfoDo) Group(cols ...field.Expr) IPaymentInfoDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentInfoDo) Having(conds ...gen.Condition) IPaymentInfoDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentInfoDo) Limit(limit int) IPaymentInfoDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentInfoDo) Offset(offset int) IPaymentInfoDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentInfoDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentInfoDo) Unscoped() IPaymentInfoDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentInfoDo) Create(values ...*models.PaymentInfo) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentInfoDo) CreateInBatches(values []*models.PaymentInfo, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentInfoDo) Save(values ...*models.PaymentInfo) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentInfoDo) First() (*models.PaymentInfo, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.PaymentInfo), nil
	}
}

func (p paymentInfoDo) Take() (*models.PaymentInfo, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.PaymentInfo), nil
	}
}

func (p paymentInfoDo) Last() (*models.PaymentInfo, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.PaymentInfo), nil
	}
}

func (p paymentInfoDo) Find() ([]*models.PaymentInfo, error) {
	result, err := p.DO.Find()
	return result.([]*models.PaymentInfo), err
}

func (p paymentInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.PaymentInfo, err error) {
	buf := make([]*models.PaymentInfo, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentInfoDo) FindInBatches(result *[]*models.PaymentInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentInfoDo) Attrs(attrs ...field.AssignExpr) IPaymentInfoDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentInfoDo) Assign(attrs ...field.AssignExpr) IPaymentInfoDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentInfoDo) Joins(fields ...field.RelationField) IPaymentInfoDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentInfoDo) Preload(fields ...field.RelationField) IPaymentInfoDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentInfoDo) FirstOrInit() (*models.PaymentInfo, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.PaymentInfo), nil
	}
}

func (p paymentInfoDo) FirstOrCreate() (*models.PaymentInfo, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.PaymentInfo), nil
	}
}

func (p paymentInfoDo) FindByPage(offset int, limit int) (result []*models.PaymentInfo, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentInfoDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentInfoDo) Delete(models ...*models.PaymentInfo) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentInfoDo) withDO(do gen.Dao) *paymentInfoDo {
	p.DO = *do.(*gen.DO)
	return p
}
