// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cloudzenith/DouTok/backend/baseService/internal/infrastructure/dal/models"
)

func newTradePromotion(db *gorm.DB, opts ...gen.DOOption) tradePromotion {
	_tradePromotion := tradePromotion{}

	_tradePromotion.tradePromotionDo.UseDB(db, opts...)
	_tradePromotion.tradePromotionDo.UseModel(&models.TradePromotion{})

	tableName := _tradePromotion.tradePromotionDo.TableName()
	_tradePromotion.ALL = field.NewAsterisk(tableName)
	_tradePromotion.ID = field.NewInt64(tableName, "id")
	_tradePromotion.PromotionID = field.NewInt64(tableName, "promotion_id")
	_tradePromotion.Amount = field.NewInt64(tableName, "amount")
	_tradePromotion.PromotionType = field.NewInt32(tableName, "promotion_type")
	_tradePromotion.AccountID = field.NewInt64(tableName, "account_id")
	_tradePromotion.IsDeleted = field.NewBool(tableName, "is_deleted")
	_tradePromotion.CreateTime = field.NewTime(tableName, "create_time")
	_tradePromotion.UpdateTime = field.NewTime(tableName, "update_time")

	_tradePromotion.fillFieldMap()

	return _tradePromotion
}

type tradePromotion struct {
	tradePromotionDo

	ALL           field.Asterisk
	ID            field.Int64 // 具体优惠id
	PromotionID   field.Int64 // 优惠id
	Amount        field.Int64 // 优惠金额，单位：厘
	PromotionType field.Int32 // 优惠类型，如满减、折扣等
	AccountID     field.Int64 // 账户id
	IsDeleted     field.Bool
	CreateTime    field.Time
	UpdateTime    field.Time

	fieldMap map[string]field.Expr
}

func (t tradePromotion) Table(newTableName string) *tradePromotion {
	t.tradePromotionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tradePromotion) As(alias string) *tradePromotion {
	t.tradePromotionDo.DO = *(t.tradePromotionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tradePromotion) updateTableName(table string) *tradePromotion {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.PromotionID = field.NewInt64(table, "promotion_id")
	t.Amount = field.NewInt64(table, "amount")
	t.PromotionType = field.NewInt32(table, "promotion_type")
	t.AccountID = field.NewInt64(table, "account_id")
	t.IsDeleted = field.NewBool(table, "is_deleted")
	t.CreateTime = field.NewTime(table, "create_time")
	t.UpdateTime = field.NewTime(table, "update_time")

	t.fillFieldMap()

	return t
}

func (t *tradePromotion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tradePromotion) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["id"] = t.ID
	t.fieldMap["promotion_id"] = t.PromotionID
	t.fieldMap["amount"] = t.Amount
	t.fieldMap["promotion_type"] = t.PromotionType
	t.fieldMap["account_id"] = t.AccountID
	t.fieldMap["is_deleted"] = t.IsDeleted
	t.fieldMap["create_time"] = t.CreateTime
	t.fieldMap["update_time"] = t.UpdateTime
}

func (t tradePromotion) clone(db *gorm.DB) tradePromotion {
	t.tradePromotionDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tradePromotion) replaceDB(db *gorm.DB) tradePromotion {
	t.tradePromotionDo.ReplaceDB(db)
	return t
}

type tradePromotionDo struct{ gen.DO }

type ITradePromotionDo interface {
	gen.SubQuery
	Debug() ITradePromotionDo
	WithContext(ctx context.Context) ITradePromotionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITradePromotionDo
	WriteDB() ITradePromotionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITradePromotionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITradePromotionDo
	Not(conds ...gen.Condition) ITradePromotionDo
	Or(conds ...gen.Condition) ITradePromotionDo
	Select(conds ...field.Expr) ITradePromotionDo
	Where(conds ...gen.Condition) ITradePromotionDo
	Order(conds ...field.Expr) ITradePromotionDo
	Distinct(cols ...field.Expr) ITradePromotionDo
	Omit(cols ...field.Expr) ITradePromotionDo
	Join(table schema.Tabler, on ...field.Expr) ITradePromotionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITradePromotionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITradePromotionDo
	Group(cols ...field.Expr) ITradePromotionDo
	Having(conds ...gen.Condition) ITradePromotionDo
	Limit(limit int) ITradePromotionDo
	Offset(offset int) ITradePromotionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITradePromotionDo
	Unscoped() ITradePromotionDo
	Create(values ...*models.TradePromotion) error
	CreateInBatches(values []*models.TradePromotion, batchSize int) error
	Save(values ...*models.TradePromotion) error
	First() (*models.TradePromotion, error)
	Take() (*models.TradePromotion, error)
	Last() (*models.TradePromotion, error)
	Find() ([]*models.TradePromotion, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TradePromotion, err error)
	FindInBatches(result *[]*models.TradePromotion, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.TradePromotion) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITradePromotionDo
	Assign(attrs ...field.AssignExpr) ITradePromotionDo
	Joins(fields ...field.RelationField) ITradePromotionDo
	Preload(fields ...field.RelationField) ITradePromotionDo
	FirstOrInit() (*models.TradePromotion, error)
	FirstOrCreate() (*models.TradePromotion, error)
	FindByPage(offset int, limit int) (result []*models.TradePromotion, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITradePromotionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tradePromotionDo) Debug() ITradePromotionDo {
	return t.withDO(t.DO.Debug())
}

func (t tradePromotionDo) WithContext(ctx context.Context) ITradePromotionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tradePromotionDo) ReadDB() ITradePromotionDo {
	return t.Clauses(dbresolver.Read)
}

func (t tradePromotionDo) WriteDB() ITradePromotionDo {
	return t.Clauses(dbresolver.Write)
}

func (t tradePromotionDo) Session(config *gorm.Session) ITradePromotionDo {
	return t.withDO(t.DO.Session(config))
}

func (t tradePromotionDo) Clauses(conds ...clause.Expression) ITradePromotionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tradePromotionDo) Returning(value interface{}, columns ...string) ITradePromotionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tradePromotionDo) Not(conds ...gen.Condition) ITradePromotionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tradePromotionDo) Or(conds ...gen.Condition) ITradePromotionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tradePromotionDo) Select(conds ...field.Expr) ITradePromotionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tradePromotionDo) Where(conds ...gen.Condition) ITradePromotionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tradePromotionDo) Order(conds ...field.Expr) ITradePromotionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tradePromotionDo) Distinct(cols ...field.Expr) ITradePromotionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tradePromotionDo) Omit(cols ...field.Expr) ITradePromotionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tradePromotionDo) Join(table schema.Tabler, on ...field.Expr) ITradePromotionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tradePromotionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITradePromotionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tradePromotionDo) RightJoin(table schema.Tabler, on ...field.Expr) ITradePromotionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tradePromotionDo) Group(cols ...field.Expr) ITradePromotionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tradePromotionDo) Having(conds ...gen.Condition) ITradePromotionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tradePromotionDo) Limit(limit int) ITradePromotionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tradePromotionDo) Offset(offset int) ITradePromotionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tradePromotionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITradePromotionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tradePromotionDo) Unscoped() ITradePromotionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tradePromotionDo) Create(values ...*models.TradePromotion) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tradePromotionDo) CreateInBatches(values []*models.TradePromotion, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tradePromotionDo) Save(values ...*models.TradePromotion) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tradePromotionDo) First() (*models.TradePromotion, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.TradePromotion), nil
	}
}

func (t tradePromotionDo) Take() (*models.TradePromotion, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.TradePromotion), nil
	}
}

func (t tradePromotionDo) Last() (*models.TradePromotion, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.TradePromotion), nil
	}
}

func (t tradePromotionDo) Find() ([]*models.TradePromotion, error) {
	result, err := t.DO.Find()
	return result.([]*models.TradePromotion), err
}

func (t tradePromotionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TradePromotion, err error) {
	buf := make([]*models.TradePromotion, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tradePromotionDo) FindInBatches(result *[]*models.TradePromotion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tradePromotionDo) Attrs(attrs ...field.AssignExpr) ITradePromotionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tradePromotionDo) Assign(attrs ...field.AssignExpr) ITradePromotionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tradePromotionDo) Joins(fields ...field.RelationField) ITradePromotionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tradePromotionDo) Preload(fields ...field.RelationField) ITradePromotionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tradePromotionDo) FirstOrInit() (*models.TradePromotion, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.TradePromotion), nil
	}
}

func (t tradePromotionDo) FirstOrCreate() (*models.TradePromotion, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.TradePromotion), nil
	}
}

func (t tradePromotionDo) FindByPage(offset int, limit int) (result []*models.TradePromotion, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tradePromotionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tradePromotionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tradePromotionDo) Delete(models ...*models.TradePromotion) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tradePromotionDo) withDO(do gen.Dao) *tradePromotionDo {
	t.DO = *do.(*gen.DO)
	return t
}
