// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cloudzenith/DouTok/backend/baseService/internal/infrastructure/dal/models"
)

func newTradeOrder(db *gorm.DB, opts ...gen.DOOption) tradeOrder {
	_tradeOrder := tradeOrder{}

	_tradeOrder.tradeOrderDo.UseDB(db, opts...)
	_tradeOrder.tradeOrderDo.UseModel(&models.TradeOrder{})

	tableName := _tradeOrder.tradeOrderDo.TableName()
	_tradeOrder.ALL = field.NewAsterisk(tableName)
	_tradeOrder.ID = field.NewInt64(tableName, "id")
	_tradeOrder.BizType = field.NewInt32(tableName, "biz_type")
	_tradeOrder.SaleWay = field.NewInt32(tableName, "sale_way")
	_tradeOrder.PaySequence = field.NewInt32(tableName, "pay_sequence")
	_tradeOrder.GoodsType = field.NewInt32(tableName, "goods_type")
	_tradeOrder.Status = field.NewInt32(tableName, "status")
	_tradeOrder.BizStatus = field.NewInt64(tableName, "biz_status")
	_tradeOrder.BizOrderNo = field.NewString(tableName, "biz_order_no")
	_tradeOrder.BizID = field.NewInt64(tableName, "biz_id")
	_tradeOrder.BuyerID = field.NewInt64(tableName, "buyer_id")
	_tradeOrder.SellerID = field.NewInt64(tableName, "seller_id")
	_tradeOrder.PayType = field.NewInt32(tableName, "pay_type")
	_tradeOrder.PayableAmount = field.NewInt64(tableName, "payable_amount")
	_tradeOrder.PaidAmount = field.NewInt64(tableName, "paid_amount")
	_tradeOrder.PromotionAmount = field.NewInt64(tableName, "promotion_amount")
	_tradeOrder.DeliveryInfoID = field.NewInt64(tableName, "delivery_info_id")
	_tradeOrder.DeliveryTime = field.NewTime(tableName, "delivery_time")
	_tradeOrder.PaymentInfoID = field.NewInt64(tableName, "payment_info_id")
	_tradeOrder.PayTime = field.NewTime(tableName, "pay_time")
	_tradeOrder.CloseTime = field.NewTime(tableName, "close_time")
	_tradeOrder.CloseType = field.NewInt32(tableName, "close_type")
	_tradeOrder.CloseReason = field.NewString(tableName, "close_reason")
	_tradeOrder.Extra = field.NewString(tableName, "extra")
	_tradeOrder.TradeOrderRelation = field.NewInt32(tableName, "trade_order_relation")
	_tradeOrder.OriginOrderID = field.NewInt64(tableName, "origin_order_id")
	_tradeOrder.ExpectPayTimeOut = field.NewTime(tableName, "expect_pay_time_out")
	_tradeOrder.ActualPayTimeOut = field.NewTime(tableName, "actual_pay_time_out")
	_tradeOrder.ExecuteAfterPayTimeOut = field.NewBool(tableName, "execute_after_pay_time_out")
	_tradeOrder.IsDeleted = field.NewBool(tableName, "is_deleted")
	_tradeOrder.CreateTime = field.NewTime(tableName, "create_time")
	_tradeOrder.UpdateTime = field.NewTime(tableName, "update_time")

	_tradeOrder.fillFieldMap()

	return _tradeOrder
}

type tradeOrder struct {
	tradeOrderDo

	ALL                    field.Asterisk
	ID                     field.Int64  // 交易单id
	BizType                field.Int32  // 业务类型，如DouTok充值、商城订单等
	SaleWay                field.Int32  // 销售方式，如直接销售、代理销售等
	PaySequence            field.Int32  // 支付顺序, 如先支付、后支付
	GoodsType              field.Int32  // 商品类型，如普通商品、虚拟商品、优惠券等
	Status                 field.Int32  // 交易单状态，如已创建、已支付、开始交付、交付完成等
	BizStatus              field.Int64  // 业务状态
	BizOrderNo             field.String // 业务订单号
	BizID                  field.Int64  // 业务id
	BuyerID                field.Int64  // 买家id
	SellerID               field.Int64  // 卖家id
	PayType                field.Int32  // 支付类型，如余额支付、微信支付、支付宝支付等
	PayableAmount          field.Int64  // 应付金额，单位：厘
	PaidAmount             field.Int64  // 已支付金额，单位：厘
	PromotionAmount        field.Int64  // 优惠金额，单位：厘
	DeliveryInfoID         field.Int64  // 发货信息id
	DeliveryTime           field.Time   // 发货时间
	PaymentInfoID          field.Int64  // 支付信息id
	PayTime                field.Time   // 支付时间
	CloseTime              field.Time   // 关单时间
	CloseType              field.Int32  // 关单类型
	CloseReason            field.String // 关单原因
	Extra                  field.String // 额外信息
	TradeOrderRelation     field.Int32  // 交易单类型
	OriginOrderID          field.Int64  // 原始订单id
	ExpectPayTimeOut       field.Time   // 预期支付超时时间
	ActualPayTimeOut       field.Time   // 实际支付超时时间
	ExecuteAfterPayTimeOut field.Bool   // 支付超时后是否执行
	IsDeleted              field.Bool
	CreateTime             field.Time
	UpdateTime             field.Time

	fieldMap map[string]field.Expr
}

func (t tradeOrder) Table(newTableName string) *tradeOrder {
	t.tradeOrderDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tradeOrder) As(alias string) *tradeOrder {
	t.tradeOrderDo.DO = *(t.tradeOrderDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tradeOrder) updateTableName(table string) *tradeOrder {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.BizType = field.NewInt32(table, "biz_type")
	t.SaleWay = field.NewInt32(table, "sale_way")
	t.PaySequence = field.NewInt32(table, "pay_sequence")
	t.GoodsType = field.NewInt32(table, "goods_type")
	t.Status = field.NewInt32(table, "status")
	t.BizStatus = field.NewInt64(table, "biz_status")
	t.BizOrderNo = field.NewString(table, "biz_order_no")
	t.BizID = field.NewInt64(table, "biz_id")
	t.BuyerID = field.NewInt64(table, "buyer_id")
	t.SellerID = field.NewInt64(table, "seller_id")
	t.PayType = field.NewInt32(table, "pay_type")
	t.PayableAmount = field.NewInt64(table, "payable_amount")
	t.PaidAmount = field.NewInt64(table, "paid_amount")
	t.PromotionAmount = field.NewInt64(table, "promotion_amount")
	t.DeliveryInfoID = field.NewInt64(table, "delivery_info_id")
	t.DeliveryTime = field.NewTime(table, "delivery_time")
	t.PaymentInfoID = field.NewInt64(table, "payment_info_id")
	t.PayTime = field.NewTime(table, "pay_time")
	t.CloseTime = field.NewTime(table, "close_time")
	t.CloseType = field.NewInt32(table, "close_type")
	t.CloseReason = field.NewString(table, "close_reason")
	t.Extra = field.NewString(table, "extra")
	t.TradeOrderRelation = field.NewInt32(table, "trade_order_relation")
	t.OriginOrderID = field.NewInt64(table, "origin_order_id")
	t.ExpectPayTimeOut = field.NewTime(table, "expect_pay_time_out")
	t.ActualPayTimeOut = field.NewTime(table, "actual_pay_time_out")
	t.ExecuteAfterPayTimeOut = field.NewBool(table, "execute_after_pay_time_out")
	t.IsDeleted = field.NewBool(table, "is_deleted")
	t.CreateTime = field.NewTime(table, "create_time")
	t.UpdateTime = field.NewTime(table, "update_time")

	t.fillFieldMap()

	return t
}

func (t *tradeOrder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tradeOrder) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 31)
	t.fieldMap["id"] = t.ID
	t.fieldMap["biz_type"] = t.BizType
	t.fieldMap["sale_way"] = t.SaleWay
	t.fieldMap["pay_sequence"] = t.PaySequence
	t.fieldMap["goods_type"] = t.GoodsType
	t.fieldMap["status"] = t.Status
	t.fieldMap["biz_status"] = t.BizStatus
	t.fieldMap["biz_order_no"] = t.BizOrderNo
	t.fieldMap["biz_id"] = t.BizID
	t.fieldMap["buyer_id"] = t.BuyerID
	t.fieldMap["seller_id"] = t.SellerID
	t.fieldMap["pay_type"] = t.PayType
	t.fieldMap["payable_amount"] = t.PayableAmount
	t.fieldMap["paid_amount"] = t.PaidAmount
	t.fieldMap["promotion_amount"] = t.PromotionAmount
	t.fieldMap["delivery_info_id"] = t.DeliveryInfoID
	t.fieldMap["delivery_time"] = t.DeliveryTime
	t.fieldMap["payment_info_id"] = t.PaymentInfoID
	t.fieldMap["pay_time"] = t.PayTime
	t.fieldMap["close_time"] = t.CloseTime
	t.fieldMap["close_type"] = t.CloseType
	t.fieldMap["close_reason"] = t.CloseReason
	t.fieldMap["extra"] = t.Extra
	t.fieldMap["trade_order_relation"] = t.TradeOrderRelation
	t.fieldMap["origin_order_id"] = t.OriginOrderID
	t.fieldMap["expect_pay_time_out"] = t.ExpectPayTimeOut
	t.fieldMap["actual_pay_time_out"] = t.ActualPayTimeOut
	t.fieldMap["execute_after_pay_time_out"] = t.ExecuteAfterPayTimeOut
	t.fieldMap["is_deleted"] = t.IsDeleted
	t.fieldMap["create_time"] = t.CreateTime
	t.fieldMap["update_time"] = t.UpdateTime
}

func (t tradeOrder) clone(db *gorm.DB) tradeOrder {
	t.tradeOrderDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tradeOrder) replaceDB(db *gorm.DB) tradeOrder {
	t.tradeOrderDo.ReplaceDB(db)
	return t
}

type tradeOrderDo struct{ gen.DO }

type ITradeOrderDo interface {
	gen.SubQuery
	Debug() ITradeOrderDo
	WithContext(ctx context.Context) ITradeOrderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITradeOrderDo
	WriteDB() ITradeOrderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITradeOrderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITradeOrderDo
	Not(conds ...gen.Condition) ITradeOrderDo
	Or(conds ...gen.Condition) ITradeOrderDo
	Select(conds ...field.Expr) ITradeOrderDo
	Where(conds ...gen.Condition) ITradeOrderDo
	Order(conds ...field.Expr) ITradeOrderDo
	Distinct(cols ...field.Expr) ITradeOrderDo
	Omit(cols ...field.Expr) ITradeOrderDo
	Join(table schema.Tabler, on ...field.Expr) ITradeOrderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITradeOrderDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITradeOrderDo
	Group(cols ...field.Expr) ITradeOrderDo
	Having(conds ...gen.Condition) ITradeOrderDo
	Limit(limit int) ITradeOrderDo
	Offset(offset int) ITradeOrderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeOrderDo
	Unscoped() ITradeOrderDo
	Create(values ...*models.TradeOrder) error
	CreateInBatches(values []*models.TradeOrder, batchSize int) error
	Save(values ...*models.TradeOrder) error
	First() (*models.TradeOrder, error)
	Take() (*models.TradeOrder, error)
	Last() (*models.TradeOrder, error)
	Find() ([]*models.TradeOrder, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TradeOrder, err error)
	FindInBatches(result *[]*models.TradeOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.TradeOrder) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITradeOrderDo
	Assign(attrs ...field.AssignExpr) ITradeOrderDo
	Joins(fields ...field.RelationField) ITradeOrderDo
	Preload(fields ...field.RelationField) ITradeOrderDo
	FirstOrInit() (*models.TradeOrder, error)
	FirstOrCreate() (*models.TradeOrder, error)
	FindByPage(offset int, limit int) (result []*models.TradeOrder, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITradeOrderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tradeOrderDo) Debug() ITradeOrderDo {
	return t.withDO(t.DO.Debug())
}

func (t tradeOrderDo) WithContext(ctx context.Context) ITradeOrderDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tradeOrderDo) ReadDB() ITradeOrderDo {
	return t.Clauses(dbresolver.Read)
}

func (t tradeOrderDo) WriteDB() ITradeOrderDo {
	return t.Clauses(dbresolver.Write)
}

func (t tradeOrderDo) Session(config *gorm.Session) ITradeOrderDo {
	return t.withDO(t.DO.Session(config))
}

func (t tradeOrderDo) Clauses(conds ...clause.Expression) ITradeOrderDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tradeOrderDo) Returning(value interface{}, columns ...string) ITradeOrderDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tradeOrderDo) Not(conds ...gen.Condition) ITradeOrderDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tradeOrderDo) Or(conds ...gen.Condition) ITradeOrderDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tradeOrderDo) Select(conds ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tradeOrderDo) Where(conds ...gen.Condition) ITradeOrderDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tradeOrderDo) Order(conds ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tradeOrderDo) Distinct(cols ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tradeOrderDo) Omit(cols ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tradeOrderDo) Join(table schema.Tabler, on ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tradeOrderDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tradeOrderDo) RightJoin(table schema.Tabler, on ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tradeOrderDo) Group(cols ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tradeOrderDo) Having(conds ...gen.Condition) ITradeOrderDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tradeOrderDo) Limit(limit int) ITradeOrderDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tradeOrderDo) Offset(offset int) ITradeOrderDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tradeOrderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeOrderDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tradeOrderDo) Unscoped() ITradeOrderDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tradeOrderDo) Create(values ...*models.TradeOrder) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tradeOrderDo) CreateInBatches(values []*models.TradeOrder, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tradeOrderDo) Save(values ...*models.TradeOrder) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tradeOrderDo) First() (*models.TradeOrder, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.TradeOrder), nil
	}
}

func (t tradeOrderDo) Take() (*models.TradeOrder, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.TradeOrder), nil
	}
}

func (t tradeOrderDo) Last() (*models.TradeOrder, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.TradeOrder), nil
	}
}

func (t tradeOrderDo) Find() ([]*models.TradeOrder, error) {
	result, err := t.DO.Find()
	return result.([]*models.TradeOrder), err
}

func (t tradeOrderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TradeOrder, err error) {
	buf := make([]*models.TradeOrder, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tradeOrderDo) FindInBatches(result *[]*models.TradeOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tradeOrderDo) Attrs(attrs ...field.AssignExpr) ITradeOrderDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tradeOrderDo) Assign(attrs ...field.AssignExpr) ITradeOrderDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tradeOrderDo) Joins(fields ...field.RelationField) ITradeOrderDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tradeOrderDo) Preload(fields ...field.RelationField) ITradeOrderDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tradeOrderDo) FirstOrInit() (*models.TradeOrder, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.TradeOrder), nil
	}
}

func (t tradeOrderDo) FirstOrCreate() (*models.TradeOrder, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.TradeOrder), nil
	}
}

func (t tradeOrderDo) FindByPage(offset int, limit int) (result []*models.TradeOrder, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tradeOrderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tradeOrderDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tradeOrderDo) Delete(models ...*models.TradeOrder) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tradeOrderDo) withDO(do gen.Dao) *tradeOrderDo {
	t.DO = *do.(*gen.DO)
	return t
}
