server:
  grpc:
    addr: 0.0.0.0:8888

data:
  database:
    source: root:root@tcp(localhost:3306)/doutok?parseTime=true
  redis:
    source: localhost:6379
    password: root
  minio:
    endpoint: localhost:9000
    accessKey: root
    secretKey: rootroot

snowflake:
  node: 1