// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: delivery_info.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DeliveryInfoServiceClient is the client API for DeliveryInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryInfoServiceClient interface {
	CreateDeliveryInfo(ctx context.Context, in *CreateDeliveryInfoRequest, opts ...grpc.CallOption) (*CreateDeliveryInfoResponse, error)
	UpdateDeliveryInfo(ctx context.Context, in *UpdateSourceDeliveryInfoRequest, opts ...grpc.CallOption) (*UpdateSourceDeliveryInfoResponse, error)
	QueryById(ctx context.Context, in *QueryByIdRequest, opts ...grpc.CallOption) (*QueryByIdResponse, error)
	QueryByAccountId(ctx context.Context, in *QueryByAccountIdRequest, opts ...grpc.CallOption) (*QueryByAccountIdResponse, error)
	DeleteDeliveryInfo(ctx context.Context, in *DeleteDeliveryInfoRequest, opts ...grpc.CallOption) (*DeleteDeliveryInfoResponse, error)
}

type deliveryInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryInfoServiceClient(cc grpc.ClientConnInterface) DeliveryInfoServiceClient {
	return &deliveryInfoServiceClient{cc}
}

func (c *deliveryInfoServiceClient) CreateDeliveryInfo(ctx context.Context, in *CreateDeliveryInfoRequest, opts ...grpc.CallOption) (*CreateDeliveryInfoResponse, error) {
	out := new(CreateDeliveryInfoResponse)
	err := c.cc.Invoke(ctx, "/api.DeliveryInfoService/CreateDeliveryInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryInfoServiceClient) UpdateDeliveryInfo(ctx context.Context, in *UpdateSourceDeliveryInfoRequest, opts ...grpc.CallOption) (*UpdateSourceDeliveryInfoResponse, error) {
	out := new(UpdateSourceDeliveryInfoResponse)
	err := c.cc.Invoke(ctx, "/api.DeliveryInfoService/UpdateDeliveryInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryInfoServiceClient) QueryById(ctx context.Context, in *QueryByIdRequest, opts ...grpc.CallOption) (*QueryByIdResponse, error) {
	out := new(QueryByIdResponse)
	err := c.cc.Invoke(ctx, "/api.DeliveryInfoService/QueryById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryInfoServiceClient) QueryByAccountId(ctx context.Context, in *QueryByAccountIdRequest, opts ...grpc.CallOption) (*QueryByAccountIdResponse, error) {
	out := new(QueryByAccountIdResponse)
	err := c.cc.Invoke(ctx, "/api.DeliveryInfoService/QueryByAccountId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryInfoServiceClient) DeleteDeliveryInfo(ctx context.Context, in *DeleteDeliveryInfoRequest, opts ...grpc.CallOption) (*DeleteDeliveryInfoResponse, error) {
	out := new(DeleteDeliveryInfoResponse)
	err := c.cc.Invoke(ctx, "/api.DeliveryInfoService/DeleteDeliveryInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryInfoServiceServer is the server API for DeliveryInfoService service.
// All implementations should embed UnimplementedDeliveryInfoServiceServer
// for forward compatibility
type DeliveryInfoServiceServer interface {
	CreateDeliveryInfo(context.Context, *CreateDeliveryInfoRequest) (*CreateDeliveryInfoResponse, error)
	UpdateDeliveryInfo(context.Context, *UpdateSourceDeliveryInfoRequest) (*UpdateSourceDeliveryInfoResponse, error)
	QueryById(context.Context, *QueryByIdRequest) (*QueryByIdResponse, error)
	QueryByAccountId(context.Context, *QueryByAccountIdRequest) (*QueryByAccountIdResponse, error)
	DeleteDeliveryInfo(context.Context, *DeleteDeliveryInfoRequest) (*DeleteDeliveryInfoResponse, error)
}

// UnimplementedDeliveryInfoServiceServer should be embedded to have forward compatible implementations.
type UnimplementedDeliveryInfoServiceServer struct {
}

func (UnimplementedDeliveryInfoServiceServer) CreateDeliveryInfo(context.Context, *CreateDeliveryInfoRequest) (*CreateDeliveryInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeliveryInfo not implemented")
}
func (UnimplementedDeliveryInfoServiceServer) UpdateDeliveryInfo(context.Context, *UpdateSourceDeliveryInfoRequest) (*UpdateSourceDeliveryInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeliveryInfo not implemented")
}
func (UnimplementedDeliveryInfoServiceServer) QueryById(context.Context, *QueryByIdRequest) (*QueryByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryById not implemented")
}
func (UnimplementedDeliveryInfoServiceServer) QueryByAccountId(context.Context, *QueryByAccountIdRequest) (*QueryByAccountIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryByAccountId not implemented")
}
func (UnimplementedDeliveryInfoServiceServer) DeleteDeliveryInfo(context.Context, *DeleteDeliveryInfoRequest) (*DeleteDeliveryInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeliveryInfo not implemented")
}

// UnsafeDeliveryInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryInfoServiceServer will
// result in compilation errors.
type UnsafeDeliveryInfoServiceServer interface {
	mustEmbedUnimplementedDeliveryInfoServiceServer()
}

func RegisterDeliveryInfoServiceServer(s grpc.ServiceRegistrar, srv DeliveryInfoServiceServer) {
	s.RegisterService(&DeliveryInfoService_ServiceDesc, srv)
}

func _DeliveryInfoService_CreateDeliveryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeliveryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryInfoServiceServer).CreateDeliveryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DeliveryInfoService/CreateDeliveryInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryInfoServiceServer).CreateDeliveryInfo(ctx, req.(*CreateDeliveryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryInfoService_UpdateDeliveryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSourceDeliveryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryInfoServiceServer).UpdateDeliveryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DeliveryInfoService/UpdateDeliveryInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryInfoServiceServer).UpdateDeliveryInfo(ctx, req.(*UpdateSourceDeliveryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryInfoService_QueryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryInfoServiceServer).QueryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DeliveryInfoService/QueryById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryInfoServiceServer).QueryById(ctx, req.(*QueryByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryInfoService_QueryByAccountId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryByAccountIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryInfoServiceServer).QueryByAccountId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DeliveryInfoService/QueryByAccountId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryInfoServiceServer).QueryByAccountId(ctx, req.(*QueryByAccountIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryInfoService_DeleteDeliveryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeliveryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryInfoServiceServer).DeleteDeliveryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DeliveryInfoService/DeleteDeliveryInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryInfoServiceServer).DeleteDeliveryInfo(ctx, req.(*DeleteDeliveryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryInfoService_ServiceDesc is the grpc.ServiceDesc for DeliveryInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.DeliveryInfoService",
	HandlerType: (*DeliveryInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeliveryInfo",
			Handler:    _DeliveryInfoService_CreateDeliveryInfo_Handler,
		},
		{
			MethodName: "UpdateDeliveryInfo",
			Handler:    _DeliveryInfoService_UpdateDeliveryInfo_Handler,
		},
		{
			MethodName: "QueryById",
			Handler:    _DeliveryInfoService_QueryById_Handler,
		},
		{
			MethodName: "QueryByAccountId",
			Handler:    _DeliveryInfoService_QueryByAccountId_Handler,
		},
		{
			MethodName: "DeleteDeliveryInfo",
			Handler:    _DeliveryInfoService_DeleteDeliveryInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery_info.proto",
}
